### ISSUE TITLE
Секция анонимный доступ 

### ISSUE THREAD

**Issue by WhyWeLive** [CollegeSchedule/cs-android#5]
Необходимо разработать секци, которая состоит из следующих модулей:

- [x] Модуль авторизации, который представляет собой отдельный fragment представленный на макете **Authentication**. Там есть кнопка **Sign In**, которая должна открывать главный модуль. А также кнопка **Sign Up**, которая должна открывать модуль регистрации.
- [x] Главный модуль, в данный момент это пустой экран, который будет доработан позже.
- [x] Модуль регистрации представляет собой модальной окно, в котором на весь размер будет отображен сканер QR кодов, должна быть возможность свернуть это окно свайпом или кнопкой закрыть на твое усмотрение. Как только код был прочитан необходимо проверить его определенным образом, в будущем будет работа с API, в данный момент нужно сделать заглушку. Если код валидный, то необходимо закрыть данное модальное окно и перерисовать модуль авторизации в соотвествии с модулем продолжения регистрации. В противном случае, если код оказался невалидным, то необходимо закрыть модальной окно и отобразить alert-диалог с надписью "данный код уже был ранее использован или не был зарегистрирован в нашей базе данных".
- [x] Модуль продолжения регистрации представляет собой экран представленный на макете **Authentication Continue**. Поле ввода почты будет заблокировано для редактирования, а над полями ввода данных будет представлена информация об аккаунте. Картинку нужно грузить произвольную по ссылке. Если пользователь нажмет на кнопку авторизации, то нужно вернуться к исходному варианту данного фрагмента.

**Comment by Banjeq** [comment]
>  представляет собой модальной окно, в котором на весь размер будет отображен сканер QR кодов
Отобрази на макете, я пока не понял как это должно выглядеть

**Comment by WhyWeLive** [comment]
@Banjeq, сегодня будет дополнен макет более подробно.
